// ================================
// ToDoList dApp frontend for Ganache CLI
// ================================

// Deployed contract address from Ganache CLI
const contractAddress = "0xCC8b299bF1B04A9485f0c4223997f8c5fff420e7";

// ABI generated by Truffle (from your JSON)
const abi = [
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "address", "name": "user", "type": "address" },
      { "indexed": false, "internalType": "string", "name": "task", "type": "string" }
    ],
    "name": "TaskAdded",
    "type": "event"
  },
  { "inputs": [], "name": "lastTask", "outputs": [{ "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "taskCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "string", "name": "_task", "type": "string" }], "name": "addTask", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [], "name": "getLastTask", "outputs": [{ "internalType": "string", "name": "", "type": "string" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getTaskCount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }
];

let provider, signer, contract, account;

// ================================
// Connect MetaMask
// ================================
document.getElementById("connectBtn").addEventListener("click", async () => {
  try {
    if (!window.ethereum) return alert("Install MetaMask first!");

    // Connect to MetaMask
    provider = new ethers.providers.Web3Provider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    signer = provider.getSigner();
    account = await signer.getAddress();

    // Initialize contract
    contract = new ethers.Contract(contractAddress, abi, signer);

    // Update wallet status
    document.getElementById("walletStatus").innerText = `✅ Wallet connected: ${account}`;

    // Load tasks
    loadTasks();
  } catch (err) {
    console.error("Connection error:", err);
    alert("Failed to connect MetaMask. Check console.");
  }
});

// ================================
// Add new task
// ================================
async function addTask() {
  if (!contract) return alert("Connect MetaMask first!");

  const taskInput = document.getElementById("taskInput");
  const task = taskInput.value.trim();
  if (!task) return alert("Enter a task!");

  try {
    const tx = await contract.addTask(task);
    await tx.wait(); // wait for transaction confirmation
    taskInput.value = "";
    loadTasks();
  } catch (err) {
    console.error("Transaction failed:", err);
    alert("Transaction failed. Check console.");
  }
}

// ================================
// Load all tasks
// ================================
async function loadTasks() {
  if (!contract) return;

  try {
    const count = await contract.getTaskCount();
    const taskList = document.getElementById("taskList");
    taskList.innerHTML = "";

    for (let i = 0; i < count; i++) {
      const task = await contract.getLastTask(); // Or use your contract method to fetch each task
      const li = document.createElement("li");
      li.innerHTML = `${task} <button onclick="removeTask(${i})">❌</button>`;
      taskList.appendChild(li);
    }
  } catch (err) {
    console.error("Failed to load tasks:", err);
  }
}

// ================================
// Remove task placeholder
// ================================
async function removeTask(index) {
  alert("Remove function not implemented in contract yet!");
}
